"""Streamlit viewer for the ClearFlight compliance traceability matrix.

Reads data/matrix.json and nothing else: no API calls, no login.
Run with: streamlit run app.py
"""

import html
import json
from collections import Counter
from pathlib import Path

import streamlit as st

MATRIX_PATH = Path(__file__).parent / "data" / "matrix.json"
PROVENANCE_PATH = Path(__file__).parent / "data" / "provenance.json"
DGCA_URL = "https://www.dgca.gov.in/digigov-portal/?baseLocale=en_US?page=5068/4998/servicename"
CATEGORIES = ["Micro", "Small", "Medium"]
NO_PART = "Not tied to a specific part"

TABLE_CSS = """
<style>
.cf-wrap { overflow-x: auto; margin-bottom: 0.5rem; }
.cf-table { width: 100%; min-width: 880px; border-collapse: collapse; table-layout: fixed;
            font-size: 0.875rem; line-height: 1.4; }
.cf-table th, .cf-table td { border: 1px solid rgba(128,128,128,0.35); padding: 0.45rem 0.55rem;
                             vertical-align: top; text-align: left; overflow-wrap: anywhere; }
.cf-table th { background: rgba(128,128,128,0.14); font-weight: 600; }
.cf-note { opacity: 0.75; }
</style>
"""

st.set_page_config(page_title="DGCA CS-UAS traceability matrix", layout="wide")


def load_rows() -> list[dict]:
    return json.loads(MATRIX_PATH.read_text(encoding="utf-8"))


def load_provenance() -> dict:
    if PROVENANCE_PATH.exists():
        return json.loads(PROVENANCE_PATH.read_text(encoding="utf-8"))
    return {}


def esc(value) -> str:
    return html.escape(str(value)) if value not in (None, "") else "-"


def html_table(headers: list[str], widths: list[int], body_rows: list[list[str]]) -> str:
    """Wrapped HTML table. Cells must already be HTML-escaped."""
    head = "".join(f'<th style="width:{w}%">{h}</th>' for h, w in zip(headers, widths))
    body = "".join("<tr>" + "".join(f"<td>{c}</td>" for c in row) + "</tr>" for row in body_rows)
    return f'<div class="cf-wrap"><table class="cf-table"><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table></div>'


GENERIC_ALTERNATIVES = {"equivalent", "equivalent standard", "any other appropriate standard",
                        "other appropriate standard"}


def standard_names(row: dict) -> list[str]:
    """Named standards in external_standard_name ('; ' between standards that must all be met,
    ' OR ' between alternatives). Open-ended alternatives such as 'equivalent' are not names."""
    if not row["external_standard_name"]:
        return []
    names = (alt.strip() for item in row["external_standard_name"].split("; ") for alt in item.split(" OR "))
    return [n for n in names if n and n.lower() not in GENERIC_ALTERNATIVES]


def involves(row: dict, stage: int) -> bool:
    return row["evaluation_stage"] in (f"Stage {stage}", "Both")


if not MATRIX_PATH.exists():
    st.error("data/matrix.json not found. Run extract.py first.")
    st.stop()

rows = load_rows()
total = len(rows)
cited = sum(r["external_standard_cited"] for r in rows)

st.html(TABLE_CSS)
st.title("DGCA CS-UAS compliance traceability matrix")
st.caption(
    "Source: Certification Scheme for Unmanned Aircraft Systems (26 Jan 2022), "
    "Part 3, Annexure A: Section 4 (Structure) and Section 5 (Material and Construction), "
    f"gazette pages 140-143. [DGCA portal]({DGCA_URL}) — search Drones/UAS for the Certification "
    "Scheme and related documents; this page does not link to it directly."
)
st.warning("**Draft output, not a substitute for engineer sign-off.**")
st.caption(
    "Independent project, not affiliated with or endorsed by DGCA. Verify against the official "
    "Gazette before relying on this for compliance decisions."
)
provenance = load_provenance()
model_text = (
    f"the {provenance.get('provider', 'AI')} model **{provenance['model']}**"
    if provenance.get("model")
    else "an AI model (not recorded)"
)
st.caption(
    f"The plain-language summaries and all classifications (evaluation types, subsystem, requirement "
    f"type, categories, external standards) were generated by {model_text} from the gazette text. "
    "The requirement, method and guidance text shown in the source view is verbatim from the source."
)
st.info(
    f"**{cited} of {total} clauses defer to an external standard** (ASTM, ISO/IEC, IS and similar) "
    "that is not included in the DGCA document."
)

search = st.text_input("Search requirement text", placeholder="e.g. fastener, vibration, fire")


def pick(title: str, values_of, pool: list[dict]) -> list[dict]:
    """Multiselect whose options are the values still possible in `pool`; returns the narrowed pool.

    `values_of(row)` returns the row's values (a clause with alternative routes has several)."""
    counts = Counter(v for r in pool for v in set(values_of(r)))
    if not counts:
        return pool
    chosen = st.multiselect(
        title,
        sorted(counts, key=lambda v: (v == NO_PART, v)),
        format_func=lambda v: f"{v} ({counts[v]})",
    )
    return [r for r in pool if not chosen or set(values_of(r)) & set(chosen)]


def types_cell(types: list[str] | None) -> str:
    """Evaluation types for one stage; alternative routes are shown joined by 'or'."""
    return "<br>or ".join(esc(t) for t in types) if types else "-"


pool = rows
with st.sidebar:
    st.header("Filters")

    # 1. UAS category. Every clause currently applies to every category, so this mainly
    #    surfaces the clauses whose verification method differs by category.
    categories = st.multiselect("UAS category", CATEGORIES)
    uniform = sum(set(r["applicable_categories"]) == set(CATEGORIES) for r in rows)
    varying_ids = [r["clause_id"] for r in rows if r["category_variation_note"]]
    st.caption(
        (f"All {total} clauses apply to every category." if uniform == total
         else f"{uniform} of {total} clauses apply to every category.")
        + (f" Verification differs by category in {', '.join(varying_ids)}." if varying_ids else "")
    )
    if categories:
        pool = [r for r in pool if set(categories) & set(r["applicable_categories"])]

    # 2-3. Subsystem, requirement type.
    pool = pick("Subsystem", lambda r: [r["subsystem_tag"] or NO_PART], pool)
    pool = pick("Requirement type", lambda r: [r["requirement_type"]], pool)

    # 4. Stage: "involves" semantics, so Stage 1 includes clauses that also have a Stage 2.
    stage_counts = {
        "Any": len(pool),
        "Stage 1": sum(involves(r, 1) for r in pool),
        "Stage 2": sum(involves(r, 2) for r in pool),
        "Both": sum(involves(r, 1) and involves(r, 2) for r in pool),
    }
    stage_labels = {
        "Any": "Any stage",
        "Stage 1": "Involves Stage 1",
        "Stage 2": "Involves Stage 2",
        "Both": "Involves both stages",
    }
    stage = st.radio(
        "Evaluation stage",
        [k for k, n in stage_counts.items() if k == "Any" or n],
        format_func=lambda k: f"{stage_labels[k]} ({stage_counts[k]})",
    )
    if stage == "Stage 1":
        pool = [r for r in pool if involves(r, 1)]
    elif stage == "Stage 2":
        pool = [r for r in pool if involves(r, 2)]
    elif stage == "Both":
        pool = [r for r in pool if involves(r, 1) and involves(r, 2)]

    # 5-6. Stage-specific evaluation types, only when that stage is in play.
    if stage in ("Stage 1", "Both"):
        pool = pick("Stage 1 evaluation type", lambda r: r["stage1_evaluation_types"] or [], pool)
    if stage in ("Stage 2", "Both"):
        pool = pick("Stage 2 evaluation type", lambda r: r["stage2_evaluation_types"] or [], pool)

    # 7. External standard by name, then the yes/no checkbox.
    pool = pick("External standard", standard_names, pool)
    only_cited = st.checkbox("Only clauses citing an external standard")

if only_cited:
    pool = [r for r in pool if r["external_standard_cited"]]
if search:
    pool = [r for r in pool if search.lower() in r["requirement_text"].lower()]
shown = pool

st.subheader(f"Showing {len(shown)} of {total} clauses")
if not shown:
    st.info("No clauses match these filters.")
    st.stop()

if categories:
    differing = [r for r in shown if r["category_variation_note"]]
    lines = "\n".join(f"- **{r['clause_id']}**: {r['category_variation_note']}" for r in differing)
    st.info(
        f"**{', '.join(categories)}**: "
        + (f"these clauses are verified differently by category:\n{lines}" if differing
           else "none of the clauses shown are verified differently by category.")
    )

# Matrix view: the classified fields.
st.html(
    html_table(
        ["Clause", "Requirement type", "Subsystem", "Plain-language summary", "Stage",
         "Stage 1 method", "Stage 2 method", "External standard", "Page"],
        [7, 11, 10, 28, 6, 10, 10, 14, 4],
        [
            [esc(r["clause_id"]), esc(r["requirement_type"]), esc(r["subsystem_tag"]),
             esc(r["plain_paraphrase"]), esc(r["evaluation_stage"]),
             types_cell(r["stage1_evaluation_types"]), types_cell(r["stage2_evaluation_types"]),
             esc(r["external_standard_name"]), esc(r["source_page"])]
            for r in shown
        ],
    )
)

# Source view: verbatim text, grouped under each parent clause (4.1, 4.2, ...).
st.subheader("Source text by clause")
parents: dict[str, list[dict]] = {}
for r in rows:
    parents.setdefault(r["clause_id"].split("(")[0], []).append(r)
shown_ids = {r["clause_id"] for r in shown}
filtered = len(shown) < total

for parent_id, members in parents.items():
    matching = [r for r in members if r["clause_id"] in shown_ids]
    if not matching:
        continue
    count = f" ({len(matching)} of {len(members)} match)" if len(matching) < len(members) else ""
    with st.expander(f"{parent_id}  {members[0]['parameter']}{count}", expanded=filtered):
        body = []
        for r in matching:
            notes = []
            if r["evaluation_alternative_note"]:
                notes.append(f"<b>Alternative route:</b> {esc(r['evaluation_alternative_note'])}")
            if r["category_variation_note"]:
                notes.append(f"<b>By category:</b> {esc(r['category_variation_note'])}")
            if r["llm_confidence_note"].strip().lower() != "none":
                notes.append(f'<span class="cf-note"><b>Model note:</b> {esc(r["llm_confidence_note"])}</span>')
            body.append(
                [f"<b>{esc(r['clause_id'])}</b>", esc(r["requirement_text"]),
                 esc(r["evaluation_method_raw"]), esc(r["guidance_text"]), "<br>".join(notes) or "-"]
            )
        st.html(
            html_table(
                ["Clause", "Requirement (verbatim)", "Method of evaluation (verbatim)",
                 "Guidance (verbatim)", "Notes"],
                [8, 24, 30, 20, 18],
                body,
            )
        )
